### ISSUE TITLE
In-game Customizable window size

### ISSUE THREAD

**Issue by flyfire2002** [flyfire2002/RimworldRPGStyleInventoryCERevival#4]

**Comment by qwebek** [comment]
@flyfire2002  Hi dude, 
sorry, what version of CE and Rimworld should i have to play this mod?
I have RW 1.1 though in releases i see only for 1.0 ...

**Comment by flyfire2002** [comment]
@qwebek Hi there, RW 1.1 should be fine? The 1.0.0.1 tag is for the mod, not for the game (I really should describe the more clearly and ofc dump the whole numbered thing). Are you able to grab it from Steam Workshop instead?

**Comment by flyfire2002** [comment]
Ahhh I double checked and the release is too old for RW 1.1. I didn't mark it incorrectly. You should just grab the whole repository  which was compiled against 1.1 afaik and put it in your mod folders.

**Comment by qwebek** [comment]
@flyfire2002 oh , i see , thanks :) ,  no i can grab only from here x_x ( 
can you please help, should i update RM to 1.2 and CE to latest and can grab from here?

**Comment by flyfire2002** [comment]
@qwebek See edit. You don;t need to go for 1.2. The current code and dlls in report should be fine for 1.1

**Comment by qwebek** [comment]
@flyfire2002 thanks man! appreciate!
P.S.
i wish RW has build-in mod manager were you can search and install)

**Comment by flyfire2002** [comment]
Fixed in the last release
